language: c
compiler:
  - clang
  - gcc

install:
  - ./travis.sh getplugins || true
  
before_script:
  - uname -a
  - ./travis.sh createdb ragnarok root
  - ./travis.sh importdb ragnarok travis
  - mysql -u root -e "SET PASSWORD FOR 'travis'@'localhost' = PASSWORD('travis');"

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./travis.sh build $CONFIGURE_FLAGS ; fi
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./travis.sh test ragnarok travis travis ; fi

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "gcrI+3sx7SFz9N0NN1Ap+qlrAJjOe9xIxMQkV78LmhBBc8wG3lkSF4ASEf7690yo3bcp0gsvkfIUL8fXl68ImOxgnVTuR7oxCkjHdtCdszsoU8eGU7Kg8H0ggq/8G6493/l6sNUgZodXJOS0oyl0hHzcf5ViVM8EcoyC9USd06U="

notifications:
  email: false

addons:
  coverity_scan:
    # GitHub project metadata
    project:
      name: "HerculesWS/Hercules"
      description: "Build submitted via Travis CI"
      #version: 1.0
    # Where email notification of build analysis results will be sent
    notification_email: "haru@dotalux.com"
    # Commands to prepare for build_command
    build_command_prepend: "./configure --enable-debug; make clean"
    # The command that will be added as an argument to "cov-build" to compile your project for analysis,
    build_command: "make"
    # Pattern to match selecting branches that will run analysis.
    branch_pattern: coverity_scan

branches:
  except:
    - rathena
